### PR TITLE
Provide styling

### PR DESCRIPTION
**Pull request by silvenon**
``` diff
-now it
+has colors!
```

### CODE REVIEW

**Comment by miketheman** [comment]
Thanks!

**Comment by silvenon** [comment]
It just occurred to me. In `punctuation.definition.inserted.diff` does `inserted` refer to the Git state (inserted/modified/deleted) or the fact that it's inserted at the beginning of the line?

**Comment by miketheman** [comment]
I'm not entirely certain. The current view with your code looks like this:

**Comment by silvenon** [comment]
Yeah, it looks good, I was just worried if my changes to `punctuation.definition.inserted.diff` were correct. I assumed that `inserted` specifies Git state, so I corrected the other ones.

But I guess it doesn't matter that much, really :smiley:

**Pull request merged**
